export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const GET_ARTICLES_START='GET_ARTICLES_START';
export const GET_ARTICLES_SUCCESS='GET_ARTICLES_SUCCESS';
export const CREATE_NEW_ARTICLE='CREATE_NEW_ARTICLE';
export const DELETE_ARTICLE='DELETE_ARTICLE';
